use_frameworks!

target 'FlexDataSource_Example' do
  pod 'FlexDataSource', :path => '../'
  pod 'fuikit', git: 'https://github.com/LithoByte/fuikit'
  pod 'LithoOperators', git: 'https://github.com/LithoByte/LithoOperators'
  target 'FlexDataSource_Tests' do
    inherit! :search_paths

    
  end
end
